style: add wrapping style on keyword
52org/garden-of-the-heart pull request #54
Opened 2023-01-27 16:57 UTC by g2hhh2ee

📄 구현 내용 설명
![chrome-capture-2023-0-28](https://user-images.githubusercontent.com/57996351/215147097-e5a1c98a-6147-432b-acf7-914531255f6f.gif)
잎새 키워드가 overflow 되면 하단으로 쌓이게 스타일주었습니다.

⛱️ 주요 변경 사항
기존 스타일
![화면 캡처 2023-01-27 234340](https://user-images.githubusercontent.com/57996351/215147154-f3a5791a-a7d5-44b5-8e13-3cd720e09eb8.png)
파일 3개를 계속 건들여보면서 scroll 옵션도 주고 해봤는데요 이게 제일 깔끔한 것 같아서 이렇게 해두었습니다.

2023-01-27 17:43 UTC, msdio requested changes
1. 저번에 잎새 최대 길이를 30자까지 늘리기로 했어서, 이 부분이 변경되어야 할 것 같아요!

2. `KeywordForm.tsx` 파일의 35번 라인에 오타가 있네요 🙂
```
handleError('* 입새를 입력해주세요');
```

3. 위에서 말한 30자로 길이를 늘리게 되면, 좀 변태같지만 아래처럼 30자 잎새를 여러개 입력하는 경우에 레이아웃도 깨지고 잎새 글자도 잘리는 것 같아요!

![ezgif com-gif-maker](https://user-images.githubusercontent.com/59170680/215156765-3093156c-ca3d-48c7-ab60-3d2c8537c445.gif)

2023-01-28 06:43 UTC, g2hhh2ee commented
> 1. 저번에 잎새 최대 길이를 30자까지 늘리기로 했어서, 이 부분이 변경되어야 할 것 같아요!
> 2. `KeywordForm.tsx` 파일의 35번 라인에 오타가 있네요 🙂
> 
> ```
> handleError('* 입새를 입력해주세요');
> ```
> 
> 3. 위에서 말한 30자로 길이를 늘리게 되면, 좀 변태같지만 아래처럼 30자 잎새를 여러개 입력하는 경우에 레이아웃도 깨지고 잎새 글자도 잘리는 것 같아요!
> 

잎새가 말 그대로 키워드 역할인데 30자로 했을 경우에 저희가 처음 생각했던 간결한 이벤트성의 '우리' '만나자' 이런 느낌이 안 날 것 같아서 10자로 해뒀습니다. 이 부분은 회의 때 얘기해볼까요?

오타는 수정해두겠습니다. 😊

2023-01-28 06:44 UTC, kibum414 approved these changes

2023-02-01 12:24 UTC, userJu commented
확인했습니다👍

2023-02-01 12:24 UTC, merged